# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 842)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1055, 791))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.tableWidget_Active = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget_Active.setMinimumSize(QtCore.QSize(450, 0))
        self.tableWidget_Active.setStyleSheet("QHeaderView::section {\n"
"    background:rgb(58, 58, 58);\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.tableWidget_Active.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_Active.setColumnCount(4)
        self.tableWidget_Active.setObjectName("tableWidget_Active")
        self.tableWidget_Active.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Active.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Active.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Active.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Active.setHorizontalHeaderItem(3, item)
        self.tableWidget_Active.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_Active.horizontalHeader().setDefaultSectionSize(112)
        self.tableWidget_Active.horizontalHeader().setHighlightSections(False)
        self.tableWidget_Active.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_Active.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableWidget_Active)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tableWidget_Expired = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget_Expired.setMinimumSize(QtCore.QSize(326, 0))
        self.tableWidget_Expired.setStyleSheet("QHeaderView::section {\n"
"    background:rgb(250, 194, 194);\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: rgb(58, 58, 58);\n"
"}")
        self.tableWidget_Expired.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_Expired.setObjectName("tableWidget_Expired")
        self.tableWidget_Expired.setColumnCount(3)
        self.tableWidget_Expired.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Expired.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Expired.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Expired.setHorizontalHeaderItem(2, item)
        self.tableWidget_Expired.horizontalHeader().setDefaultSectionSize(108)
        self.tableWidget_Expired.horizontalHeader().setHighlightSections(False)
        self.tableWidget_Expired.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableWidget_Expired)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 2, 20, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.label_Table = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        self.label_Table.setFont(font)
        self.label_Table.setStyleSheet("QLabel{\n"
"    background-color: rgb(192, 206, 255);\n"
"    border: 1px solid;\n"
"    border-color: rgb(38, 34, 34);\n"
"    padding: 2px;\n"
"    padding-left: 7px;\n"
"    border-radius: 15px;\n"
"}")
        self.label_Table.setObjectName("label_Table")
        self.gridLayout.addWidget(self.label_Table, 8, 1, 1, 1)
        self.textLine_TagId = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.textLine_TagId.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.textLine_TagId.setFont(font)
        self.textLine_TagId.setObjectName("textLine_TagId")
        self.gridLayout.addWidget(self.textLine_TagId, 5, 1, 1, 1)
        self.label_Drink = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        self.label_Drink.setFont(font)
        self.label_Drink.setStyleSheet("QLabel{\n"
"    background-color: rgb(192, 206, 255);\n"
"    border: 1px solid;\n"
"    border-color: rgb(38, 34, 34);\n"
"    padding: 2px;\n"
"    padding-left: 7px;\n"
"    border-radius: 15px;\n"
"}")
        self.label_Drink.setObjectName("label_Drink")
        self.gridLayout.addWidget(self.label_Drink, 12, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 11, 1, 1, 1)
        self.label_Tag = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        self.label_Tag.setFont(font)
        self.label_Tag.setStyleSheet("QLabel{\n"
"    background-color: rgb(192, 206, 255);\n"
"    border: 1px solid;\n"
"    border-color: rgb(38, 34, 34);\n"
"    padding: 2px;\n"
"    padding-left: 7px;\n"
"    border-radius: 15px;\n"
"}")
        self.label_Tag.setObjectName("label_Tag")
        self.gridLayout.addWidget(self.label_Tag, 3, 1, 1, 1)
        self.label_time = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("QLabel{\n"
"    background-color: white;\n"
"    border: 1px solid;\n"
"    border-color: rgb(38, 34, 34);\n"
"    padding: 1px;\n"
"    padding-left: auto;\n"
"    padding-right: auto;\n"
"    border-radius: 21px;\n"
"}")
        self.label_time.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_time.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_time.setLineWidth(1)
        self.label_time.setMidLineWidth(0)
        self.label_time.setObjectName("label_time")
        self.gridLayout.addWidget(self.label_time, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 19, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 15, 1, 1, 1)
        self.textLine_TableNumber = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.textLine_TableNumber.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.textLine_TableNumber.setFont(font)
        self.textLine_TableNumber.setText("")
        self.textLine_TableNumber.setObjectName("textLine_TableNumber")
        self.gridLayout.addWidget(self.textLine_TableNumber, 9, 1, 1, 1)
        self.pushButton_Add = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Add.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Add.setFont(font)
        self.pushButton_Add.setStyleSheet("QPushButton {\n"
"    background-color: rgb(5, 140, 5);\n"
"    border: 1px solid;\n"
"    border-color: rgb(38, 34, 34);\n"
"    padding-top: 3px;\n"
"    color: rgb(124, 255, 135);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(124, 255, 135);\n"
"    border: 1px solid;\n"
"    border-color: rgb(38, 34, 34);\n"
"    color: rgb(5, 140, 5);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(124, 255, 135);\n"
"    color: rgb(241, 241, 241);\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: rgb(182, 182, 182);\n"
"    color:rgb(31, 31, 31);\n"
"}")
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.gridLayout.addWidget(self.pushButton_Add, 16, 1, 1, 1)
        self.textLine_Drink = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.textLine_Drink.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.textLine_Drink.setFont(font)
        self.textLine_Drink.setObjectName("textLine_Drink")
        self.gridLayout.addWidget(self.textLine_Drink, 14, 1, 1, 1)
        self.pushButton_Delete = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Delete.setMinimumSize(QtCore.QSize(130, 45))
        self.pushButton_Delete.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Delete.setFont(font)
        self.pushButton_Delete.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_Delete.setStyleSheet("QPushButton {\n"
"    background-color:rgb(214, 69, 69);\n"
"    border: 1px solid;\n"
"    padding-top: 2px;\n"
"    color: rgb(255, 198, 198);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 198, 198);\n"
"    color: rgb(214, 69, 69);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(255, 179, 179);\n"
"    color: rgb(249, 249, 249);\n"
"}")
        self.pushButton_Delete.setCheckable(False)
        self.pushButton_Delete.setAutoDefault(False)
        self.pushButton_Delete.setObjectName("pushButton_Delete")
        self.gridLayout.addWidget(self.pushButton_Delete, 1, 2, 1, 1)
        self.pushButton_Edit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Edit.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Edit.setFont(font)
        self.pushButton_Edit.setStyleSheet("QPushButton {\n"
"    background-color: rgb(240, 240, 240);\n"
"    border: 2px solid;\n"
"    border-color: rgb(38, 34, 34);    \n"
"    padding-top: 1px;\n"
"    color: rgb(43, 43, 43);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(230, 230, 230);\n"
"    border: 2px solid;\n"
"    border-color: rgb(38, 34, 34);    \n"
"    color: rgb(43, 43, 43);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(104, 104, 104);\n"
"    color: rgb(240, 240, 240);\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: rgb(182, 182, 182);\n"
"    color:rgb(31, 31, 31);\n"
"}")
        self.pushButton_Edit.setObjectName("pushButton_Edit")
        self.gridLayout.addWidget(self.pushButton_Edit, 18, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 17, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1072, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget_Active.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "č. stolu"))
        item = self.tableWidget_Active.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "nápoj"))
        item = self.tableWidget_Active.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "č. tácku"))
        item = self.tableWidget_Active.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "čas"))
        item = self.tableWidget_Expired.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "č. stolu"))
        item = self.tableWidget_Expired.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "nápoj"))
        item = self.tableWidget_Expired.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "č. tácku"))
        self.label_Table.setText(_translate("MainWindow", "Číslo stolu"))
        self.label_Drink.setText(_translate("MainWindow", "Nápoj"))
        self.label_Tag.setText(_translate("MainWindow", "Číslo tácku"))
        self.label_time.setText(_translate("MainWindow", "Time"))
        self.pushButton_Add.setText(_translate("MainWindow", "Přidat"))
        self.pushButton_Delete.setText(_translate("MainWindow", "ODSTRANIT"))
        self.pushButton_Edit.setText(_translate("MainWindow", "Upravit"))
